[versions]
kotlin = "1.6.21"
kotest = "5.5.2"

[libraries]
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
gradle-plugin-idea-ext = { group = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext", name = "gradle-idea-ext", version = "1.0" }
gradle-plugin-kotlin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotest = ["kotest-assertions", "kotest-runner-junit5"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
downloaddeps = { id = "uk.org.lidalia.downloaddependencies", version = "0.3.0" }
